"""test relationships 3

Revision ID: 208b64beaac3
Revises: 1aa5434211c6
Create Date: 2022-09-07 20:35:09.137872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208b64beaac3'
down_revision = '1aa5434211c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
