"""add description to Order

Revision ID: 6472ae274a41
Revises: ab99f135d5cf
Create Date: 2022-09-07 16:14:12.877507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6472ae274a41'
down_revision = 'ab99f135d5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('description', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'description')
    # ### end Alembic commands ###
