"""add back population

Revision ID: d58aeda601b0
Revises: c4921838f235
Create Date: 2022-09-07 17:19:30.316782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd58aeda601b0'
down_revision = 'c4921838f235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('service_id', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('order_id', sa.Integer(), nullable=True))
    op.drop_column('services', 'order_item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('order_item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'order_id')
    op.drop_column('order_items', 'service_id')
    # ### end Alembic commands ###
