"""add back population

Revision ID: db97cd217efa
Revises: e20eb533339e
Create Date: 2022-09-07 17:04:58.490133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db97cd217efa'
down_revision = 'e20eb533339e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
