"""add back population

Revision ID: e20eb533339e
Revises: ff05f22da4af
Create Date: 2022-09-07 16:54:51.906631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e20eb533339e'
down_revision = 'ff05f22da4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_ibfk_2', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_ibfk_1', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'order_id')
    op.drop_column('order_items', 'service_id')
    op.add_column('services', sa.Column('order_item_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'order_item_id')
    op.add_column('order_items', sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('order_items_ibfk_1', 'order_items', 'order', ['order_id'], ['id'])
    op.create_foreign_key('order_items_ibfk_2', 'order_items', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###
