"""add relation order_item service

Revision ID: ff05f22da4af
Revises: 6472ae274a41
Create Date: 2022-09-07 16:21:31.158049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff05f22da4af'
down_revision = '6472ae274a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'service_id')
    # ### end Alembic commands ###
